/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fees_Management_Systems;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;

/**
 *
 * @author Admin
 */
public class PrintReciept extends javax.swing.JFrame {

    /**
     * Creates new form PrintReciept
     */
    public PrintReciept() {
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
         getRecord();
    }
    
      
    public void getRecord()
    {
        try
        {
            Connection con = MYSQLConnection.getmysqlConnection();
            PreparedStatement pst=con.prepareStatement("select * from fees_details order by reciept_no desc limit 1");
            ResultSet rs= pst.executeQuery();
            rs.next();
            
            txt_receipt_num1.setText(rs.getString("reciept_no"));
            txt_mode_payment.setText(rs.getString("payment_mode"));
            
            String paymentMode = rs.getString("payment_mode");
            
            if(paymentMode.equalsIgnoreCase("cash"))
            {
                lbl_dd_num1.setText("");
                txt_dd_num.setText("-");
                lbl_cheque_num1.setText("cheque_no");
                txt_cheque_num.setText("-");
                txt_bank_name.setText("-");
            }
            
             if(paymentMode.equalsIgnoreCase("cheque"))
            {
                lbl_dd_num1.setText("");
                txt_dd_num.setText("");
                lbl_cheque_num1.setText("cheque_no");
                txt_cheque_num.setText(rs.getString("cheque_no"));
                txt_bank_name.setText(rs.getString("bank_name"));
            }
             
             if(paymentMode.equalsIgnoreCase("dd"))
            {
                lbl_dd_num1.setText("DD_no");
                txt_dd_num.setText(rs.getString("DD_no"));
                lbl_cheque_num1.setText("");
                txt_cheque_num.setText("");
                txt_bank_name.setText(rs.getString("bank_name"));
            }
             
               if(paymentMode.equalsIgnoreCase("Card"))
            {
                lbl_dd_num1.setText("DD_no");
                txt_dd_num.setText("-");
                lbl_cheque_num1.setText("");
                txt_cheque_num.setText("");
                txt_bank_name.setText(rs.getString("bank_name"));
            }
               txt_r_n.setText(rs.getString("student_name"));
               txt_date.setText(rs.getString("date"));
               txt_gstin.setText(rs.getString("gstin"));
               txt_year1.setText(rs.getString("year1"));
               txt_year2.setText(rs.getString("year2"));
               txt_roll_no.setText(rs.getString("roll_no"));
               txt_initialAmount.setText(rs.getString("amount"));
               txt_cgst.setText(rs.getString("cgst"));
               txt_sgst.setText(rs.getString("sgst"));
               txt_courseName.setText(rs.getString("course_name"));
               txt_total.setText(rs.getString("total_amount"));
               txt_totalInWords.setText(rs.getString("total_in_words"));
               txt_remark.setText(rs.getString("remark"));
              
        }
        catch (Exception e)
                {
                    e.printStackTrace();
                }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panel_print4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txt_year2 = new javax.swing.JLabel();
        txt_mode_payment = new javax.swing.JLabel();
        txt_dd_num = new javax.swing.JLabel();
        txt_cheque_num = new javax.swing.JLabel();
        txt_bank_name = new javax.swing.JLabel();
        txt_r_n = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        txt_gstin = new javax.swing.JLabel();
        txt_roll_no = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_receipt_num1 = new javax.swing.JLabel();
        lbl_mode_payment1 = new javax.swing.JLabel();
        lbl_dd_num1 = new javax.swing.JLabel();
        lbl_cheque_num1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbl_bank_name1 = new javax.swing.JLabel();
        lbl_r_n1 = new javax.swing.JLabel();
        txt_courseName = new javax.swing.JLabel();
        lbl_gstin1 = new javax.swing.JLabel();
        lbl_date1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_initialAmount = new javax.swing.JLabel();
        txt_sgst = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txt_total = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_totalInWords = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txt_remark = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txt_receipt_num1 = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Home");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Edit Course");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("View All Record");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Search Record");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Logout");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Update Fees");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(102, 102, 102));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Back");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(102, 102, 102));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Print");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 710));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Print Receipt");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 250, 60));

        panel_print4.setBackground(new java.awt.Color(255, 255, 255));
        panel_print4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 102));
        jLabel15.setText("College Of Computer Education");
        panel_print4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 310, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 102));
        jLabel16.setText("P.K. Roy Memorial College, Main Road, Lohar Kulli Saraidhela, Dhanbad, Jharkhand 826004");
        panel_print4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 450, 20));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 0, 102));
        jLabel17.setText("P.K. Roy Memorial College ");
        panel_print4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 230, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 102));
        jLabel14.setText("Binod Bihari Mahto Koyalanchal University , Dhanbad");
        panel_print4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 320, 20));

        jPanel6.setBackground(new java.awt.Color(51, 0, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        panel_print4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 700, 6));

        txt_year2.setForeground(new java.awt.Color(51, 0, 102));
        txt_year2.setText("2021");
        panel_print4.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 78, 21));

        txt_mode_payment.setForeground(new java.awt.Color(51, 0, 102));
        txt_mode_payment.setText("Mode of Payment :");
        panel_print4.add(txt_mode_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 105, 21));

        txt_dd_num.setForeground(new java.awt.Color(51, 0, 102));
        txt_dd_num.setText("DD No :");
        panel_print4.add(txt_dd_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 105, 21));

        txt_cheque_num.setForeground(new java.awt.Color(51, 0, 102));
        txt_cheque_num.setText("Cheque No :");
        panel_print4.add(txt_cheque_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 100, 21));

        txt_bank_name.setForeground(new java.awt.Color(51, 0, 102));
        txt_bank_name.setText("Bank Name :");
        panel_print4.add(txt_bank_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 160, 21));

        txt_r_n.setForeground(new java.awt.Color(51, 0, 102));
        txt_r_n.setText("Recieved From :");
        panel_print4.add(txt_r_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 130, 21));

        jLabel18.setForeground(new java.awt.Color(51, 0, 102));
        jLabel18.setText("Recieved From For The Given Year :");
        panel_print4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, 21));

        txt_date.setForeground(new java.awt.Color(51, 0, 102));
        txt_date.setText("Date:");
        panel_print4.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 70, 21));

        txt_gstin.setForeground(new java.awt.Color(51, 0, 102));
        txt_gstin.setText("GSTIN :");
        panel_print4.add(txt_gstin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 100, 21));

        txt_roll_no.setForeground(new java.awt.Color(51, 0, 102));
        txt_roll_no.setText("Roll No :");
        panel_print4.add(txt_roll_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 130, 21));

        jSeparator1.setBackground(new java.awt.Color(51, 0, 102));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        panel_print4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 720, 16));

        jSeparator2.setBackground(new java.awt.Color(51, 0, 102));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        panel_print4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 720, 20));

        lbl_receipt_num1.setForeground(new java.awt.Color(51, 0, 102));
        lbl_receipt_num1.setText("Receipt No : ");
        panel_print4.add(lbl_receipt_num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 78, 21));

        lbl_mode_payment1.setForeground(new java.awt.Color(51, 0, 102));
        lbl_mode_payment1.setText("Mode of Payment :");
        panel_print4.add(lbl_mode_payment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 105, 21));

        lbl_dd_num1.setForeground(new java.awt.Color(51, 0, 102));
        lbl_dd_num1.setText("DD No :");
        panel_print4.add(lbl_dd_num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 105, 21));

        lbl_cheque_num1.setForeground(new java.awt.Color(51, 0, 102));
        lbl_cheque_num1.setText("Cheque No :");
        panel_print4.add(lbl_cheque_num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 105, 21));

        jLabel19.setForeground(new java.awt.Color(51, 0, 102));
        jLabel19.setText("  to");
        panel_print4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 78, 21));

        lbl_bank_name1.setForeground(new java.awt.Color(51, 0, 102));
        lbl_bank_name1.setText("Bank Name :");
        panel_print4.add(lbl_bank_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 78, 21));

        lbl_r_n1.setForeground(new java.awt.Color(51, 0, 102));
        lbl_r_n1.setText("Recieved From :");
        panel_print4.add(lbl_r_n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 100, 21));

        txt_courseName.setForeground(new java.awt.Color(51, 0, 102));
        txt_courseName.setText("1");
        panel_print4.add(txt_courseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 230, 21));

        lbl_gstin1.setForeground(new java.awt.Color(51, 0, 102));
        lbl_gstin1.setText("GSTIN :");
        panel_print4.add(lbl_gstin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 70, 21));

        lbl_date1.setForeground(new java.awt.Color(51, 0, 102));
        lbl_date1.setText("Date:");
        panel_print4.add(lbl_date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 70, 21));

        jLabel20.setForeground(new java.awt.Color(51, 0, 102));
        jLabel20.setText("Heads");
        panel_print4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 78, 21));

        jLabel22.setForeground(new java.awt.Color(51, 0, 102));
        jLabel22.setText("Roll No :");
        panel_print4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 70, 21));

        jLabel23.setForeground(new java.awt.Color(51, 0, 102));
        jLabel23.setText("Roll No :");
        panel_print4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 70, 21));

        jLabel24.setForeground(new java.awt.Color(51, 0, 102));
        jLabel24.setText("Amount (rs)");
        panel_print4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 78, 21));

        jLabel25.setForeground(new java.awt.Color(51, 0, 102));
        jLabel25.setText("Sr. No");
        panel_print4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 78, 21));

        jLabel26.setForeground(new java.awt.Color(51, 0, 102));
        jLabel26.setText("1");
        panel_print4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 78, 21));

        txt_initialAmount.setForeground(new java.awt.Color(51, 0, 102));
        txt_initialAmount.setText("xyz");
        panel_print4.add(txt_initialAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 78, 21));

        txt_sgst.setForeground(new java.awt.Color(51, 0, 102));
        txt_sgst.setText("SGST ");
        panel_print4.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 78, 21));

        txt_cgst.setForeground(new java.awt.Color(51, 0, 102));
        txt_cgst.setText("CGST ");
        panel_print4.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 78, 21));

        jLabel27.setForeground(new java.awt.Color(51, 0, 102));
        jLabel27.setText("CGST 7%");
        panel_print4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 78, 21));

        jLabel28.setForeground(new java.awt.Color(51, 0, 102));
        jLabel28.setText("SGST 7%");
        panel_print4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 78, 21));

        jSeparator6.setForeground(new java.awt.Color(51, 0, 102));
        panel_print4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, 210, 20));

        txt_total.setForeground(new java.awt.Color(51, 0, 102));
        txt_total.setText("Total :");
        panel_print4.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 140, 21));

        jLabel29.setForeground(new java.awt.Color(51, 0, 102));
        jLabel29.setText("Total :");
        panel_print4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 40, 21));

        txt_totalInWords.setForeground(new java.awt.Color(51, 0, 102));
        txt_totalInWords.setText("Total In Words :");
        panel_print4.add(txt_totalInWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 270, 21));

        jLabel30.setForeground(new java.awt.Color(51, 0, 102));
        jLabel30.setText("Total In Words :");
        panel_print4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 100, 21));

        jLabel31.setForeground(new java.awt.Color(51, 0, 102));
        jLabel31.setText("Receiver Signature");
        panel_print4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 110, 21));

        jSeparator7.setForeground(new java.awt.Color(51, 0, 102));
        panel_print4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 210, 20));

        txt_remark.setForeground(new java.awt.Color(51, 0, 102));
        txt_remark.setText("Remark :");
        panel_print4.add(txt_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 80, 21));

        jLabel32.setForeground(new java.awt.Color(51, 0, 102));
        jLabel32.setText("Remark :");
        panel_print4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 80, 21));

        txt_receipt_num1.setForeground(new java.awt.Color(51, 0, 102));
        txt_receipt_num1.setText("xyz");
        panel_print4.add(txt_receipt_num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 78, 21));

        txt_year1.setForeground(new java.awt.Color(51, 0, 102));
        txt_year1.setText("2021");
        panel_print4.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 78, 21));

        jPanel3.add(panel_print4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 710, 610));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 710, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        HomePage home = new HomePage();
        home.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        EditCourse course = new EditCourse();
        course.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        ViewAllRecords records = new ViewAllRecords();
        records.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        SearchRecord record = new SearchRecord();
        record.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        Login in = new Login();
        in.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        UpdateFeesDetails fee = new UpdateFeesDetails();
        fee.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        HomePage home = new HomePage();
        home.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");

        job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                pf.setOrientation(PageFormat.LANDSCAPE);
                if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);

                panel_print4.print(g2);

                return Printable.PAGE_EXISTS;

            }
        });
        boolean ok = job.printDialog();
        if(ok){
            try{

                job.print();
            }
            catch (PrinterException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lbl_bank_name1;
    private javax.swing.JLabel lbl_cheque_num1;
    private javax.swing.JLabel lbl_date1;
    private javax.swing.JLabel lbl_dd_num1;
    private javax.swing.JLabel lbl_gstin1;
    private javax.swing.JLabel lbl_mode_payment1;
    private javax.swing.JLabel lbl_r_n1;
    private javax.swing.JLabel lbl_receipt_num1;
    private javax.swing.JPanel panel_print4;
    private javax.swing.JLabel txt_bank_name;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_cheque_num;
    private javax.swing.JLabel txt_courseName;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_dd_num;
    private javax.swing.JLabel txt_gstin;
    private javax.swing.JLabel txt_initialAmount;
    private javax.swing.JLabel txt_mode_payment;
    private javax.swing.JLabel txt_r_n;
    private javax.swing.JLabel txt_receipt_num1;
    private javax.swing.JLabel txt_remark;
    private javax.swing.JLabel txt_roll_no;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel txt_totalInWords;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
